server:
 port: 8085

spring:
  application:
    name: traffic-manager

  datasource:
   url: jdbc:postgresql://localhost:5432/postgres
   username: postgres
   password: Shivprasad1!

   jpa:
    show-sql: true
    hibernate.ddl-auto: update
